#!/bin/sh

echo "Starting postinst"

# Check if user already exists
if ! id -u counter > /dev/null 2>&1; then
    useradd --system counter
fi

systemctl daemon-reload
systemctl enable counter.service
systemctl start counter
systemctl status counter


echo "postinst complete"