#!/bin/sh

echo "Starting Deb package Build"

# Check if user already exists
if ! id -u user > /dev/null 2>&1; then
    useradd --system user
fi

systemctl enable counter.service
systemctl start counter
systemctl status counter
systemctl daemon-reload

echo "Deb package Build completed"