#!/bin/sh

echo "Installing..."

# Check if counter.py already exists and is executable
if [ ! -x /usr/local/bin/counter.py ]; then
    cp bin/counter.py /usr/local/bin/counter.py
    chmod +x /usr/local/bin/counter.py
fi

# Check if counter.service already exists
if [ ! -f /etc/systemd/system/counter.service ]; then
    cp usr/bin/counter.service /etc/systemd/system/counter.service
fi
echo "Installed"