#!/bin/sh

echo "Stopping service"

# Check if counter.service already exists
if [ -f /etc/systemd/system/counter.service ]; then
    systemctl stop counter.service
    systemctl disable counter.service
fi

echo "Removing..."

if [ -f /tmp/currentCount.out ]; then
    rm /tmp/currentCount.out
else
    echo "File /tmp/currentCount.out does not exist"
fi

systemctl daemon-reload