#!/bin/sh

echo "Stopping service"
if service counter status >/dev/null 2>&1; then
    service counter stop
fi

# Check if counter.service already exists
if [ -f /etc/systemd/system/counter.service ]; then
    systemctl stop counter.service
    systemctl disable counter.service
fi

if [ -f /etc/systemd/system/counter.service ]; then
    rm /etc/systemd/system/counter.service
fi

if id -u counter > /dev/null 2>&1; then
    userdel counter
fi

if [ -f /tmp/currentCount.out ]; then
    rm /tmp/currentCount.out
fi

if [ -f /usr/local/bin/counter.py ]; then
    rm /usr/local/bin/counter.py
fi

if [ -f /lib/systemd/system/counter.service ]; then
    rm /lib/systemd/system/counter.service
fi

if id -u user > /dev/null 2>&1; then
    userdel user
fi

systemctl daemon-reload